import { test, expect } from '@playwright/test';

test.only('test', async ({ page }) => {
  await page.goto('https://www.google.com/');
  await page.getByRole('combobox', { name: 'Search' }).click();
  await page.getByRole('combobox', { name: 'Search' }).fill('sachin');
  await page.getByText('Sachin Tendulkar', { exact: true }).click();
  await page.locator('iframe[name="a-dlzveuse4kfo"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="0"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="3"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-dlzveuse4kfo"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('#JTPWx').getByRole('link', { name: 'Stats' }).click();
  await page.getByText('*').first().click();
  await page.getByRole('link', { name: 'Wikipedia', exact: true }).click();
  await page.getByRole('link', { name: 'captained the Indian national' }).click();
  await page.getByRole('link', { name: 'India national cricket team selectors' }).click();
  await expect(page.locator('#firstHeading').getByText('India national cricket team')).toBeVisible();
  await page.locator('#firstHeading').getByText('India national cricket team').click();
  await expect(page.locator('#mw-content-text')).toContainText('Indian national cricket selectors');
  await expect(page.getByRole('radio', { name: 'Small' })).not.toBeChecked();
  await page.getByText('Small', { exact: true }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('img').click();
  await page.locator('body').click();
  await page.getByRole('img').click();
  await page.goto('https://en.wikipedia.org/wiki/India_national_cricket_team_selectors');
});